### ISSUE TITLE
Plugin returns a CNI v0.2.0 response, which is quite old.

### ISSUE THREAD

**Issue by nkinkade** [m-lab/index2ip#8]
When investigating an issue with multus-cni in the new HA k8s master cluster I realized that we had defined all of our `NetworkAttachmentDefinition` objects with `cniVersion: "0.3.0"`, yet index2ip returns data formatted for version `0.2.0`. The workaround was to simply change our `NetworkAttachmentDefinition`s to use 0.2.0. However, the 0.2.0 spec is fairly old now. We may like to consider bringing it up to version 0.3.0.

There is even a version 0.4.0, but it appears that the data format is identical between 0.3.0 and 0.4.0.

**Comment by stephen-soltesz** [comment]
For reference: https://github.com/containernetworking/cni/blob/master/SPEC.md

**Comment by pboothe** [comment]
cniVersion 3.1 is likely the right one to target. However, right now this is going to be embedded in the configs at https://github.com/m-lab/k8s-support/blob/master/manage-cluster/network/multus.yml , which are themselves 0.2.0 configs. So it looks like we will have to upgrade those configs at the same time we upgrade this system.  Upgrading just became a bigger job, so I am going to punt for a while as long as this version keeps working.  There's a version that *should* work in the cni3.1 branch, but I'm not going to submit it for review until we are ready to do the rest of the required work.
